// File generated by FlutterFire CLI & Firebase SDK config.
// Do not manually modify this file unless updating project configurations.
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static const String projectId = 'zalavadiya-wedding-app';
  static const String apiKey = 'AIzaSyCA0FEdutQsfXaXrH7hNHpXsIUA8uj-N1E';
  static const String appId = '1:922368429011:web:672919b57a19c778e0fd26';
  static const String messagingSenderId = '922368429011';
  static const String authDomain = 'zalavadiya-wedding-app.firebaseapp.com';
  static const String storageBucket = 'zalavadiya-wedding-app.firebasestorage.app';
  static const String measurementId = 'G-BSEY04G5L3';
}
